import { StyleConfig, StylesState, ThemeColor } from './types';

export const THEME_COLORS: ThemeColor[] = [
  { id: 'blue', label: 'Azul', color: '#2563eb', rgb: '37 99 235' }, // blue-600
  { id: 'indigo', label: 'Índigo', color: '#4f46e5', rgb: '79 70 229' }, // indigo-600
  { id: 'violet', label: 'Violeta', color: '#7c3aed', rgb: '124 58 237' }, // violet-600
  { id: 'rose', label: 'Rosa', color: '#e11d48', rgb: '225 29 72' }, // rose-600
  { id: 'amber', label: 'Ámbar', color: '#d97706', rgb: '217 119 6' }, // amber-600
  { id: 'emerald', label: 'Esmeralda', color: '#059669', rgb: '5 150 105' }, // emerald-600
  { id: 'cyan', label: 'Cian', color: '#0891b2', rgb: '8 145 178' }, // cyan-600
  { id: 'slate', label: 'Pizarra', color: '#475569', rgb: '71 85 105' }, // slate-600
];


export const DEFAULT_STYLE: StyleConfig = {
  fontFamily: "'Poppins', sans-serif",
  fontSize: 14,
  color: '#000000',
  fontWeight: 'normal',
  fontStyle: 'normal',
  textDecoration: 'none',
  textTransform: 'none',
};

export const INITIAL_STYLES: StylesState = {
  title: {
    ...DEFAULT_STYLE,
    fontSize: 44,
    fontWeight: 'bold',
    color: '#000000',
    textTransform: 'uppercase',
  },
  header: {
    ...DEFAULT_STYLE,
    fontSize: 14,
    color: '#FFFFFF',
    backgroundColor: '#4a6da7',
    fontWeight: 'bold',
    textTransform: 'uppercase',
  },
  cell: {
    ...DEFAULT_STYLE,
    fontSize: 14,
    color: '#000000',
  },
  footer: {
    ...DEFAULT_STYLE,
    fontSize: 12,
    color: '#000000',
    fontStyle: 'italic',
  },
  footerText: 'Marcos 13:34 "y le dio a cada uno su trabajo, y al portero le ordenó que estuviera siempre vigilante"',
};

export const TRANSLATIONS = {
  es: {
    appTitle: "Hub Teocrático JW",
    selectTemplate: "Seleccionar Plantilla",
    templateUshers: "Acomodadores",
    templateCleaning: "Aseo",
    templateWeekend: "Reunión Fin de Semana",
    templateAudioVideo: "Audio y Video",
    banner: "Banner",
    uploadBanner: "Subir Banner",
    content: "CONTENIDO",
    styles: "ESTILOS",
    typography: "Tipografía",
    color: "Color",
    background: "Fondo",
    size: "Tamaño",
    mainTitle: "Título Principal",
    tableHeaders: "Encabezados de Tabla",
    cellContent: "Contenido de Celdas",
    footer: "Pie de Página",
    footerText: "Texto del pie de página",
    previewPlaceholder: "Aquí se mostrará el banner",
    door: "PUERTA",
    auditorium: "AUDITORIO",
    mic1: "Micrófono 1",
    mic2: "Micrófono 2",
    group: "GRUPO",
    president: "PRESIDENTE",
    speaker: "ORADOR",
    wtTheme: "TEMA DE LA ATALAYA",
    reader: "LECTOR",
    week: "Semana",
    month: "Mes",
    year: "Año",
    meetingDay: "Día de sus reuniones",
    createNewMonth: "Crear Nuevo Mes",
    remove: "Eliminar",
    addWeek: "Añadir Semana",
    previewTitleUshers: "Programa de Acomodadores",
    previewTitleCleaning: "Programa de Aseo",
    previewTitleWeekend: "Programa de Reunión de Fin de Semana",
    previewTitleAudioVideo: "Programa de Audio y Video",
    responsible: "RESPONSABLE",
    importExcel: "Importar Excel",
    assignedGroup: "GRUPO ASIGNADO",
    groupName: "Nombre del Grupo",
    newMonth: "Nuevo Mes",
    noDatesTitle: "No se generaron fechas",
    noDatesDesc: "Selecciona los días de la semana en los ajustes del mes (⚙️) para generar automáticamente las filas del programa.",
    assembly: "ASAMBLEA",
    loadWatchtowerThemes: "Cargar Temas de La Atalaya",
    loadingThemes: "Cargando temas...",
    themesLoaded: "Temas de La Atalaya cargados con éxito",
  },
  en: {
    appTitle: "Hub Teocrático JW",
    selectTemplate: "Select Template",
    templateUshers: "Ushers",
    templateCleaning: "Cleaning",
    templateWeekend: "Weekend Meeting",
    templateAudioVideo: "Audio & Video",
    banner: "Banner",
    uploadBanner: "Upload Banner",
    content: "CONTENT",
    styles: "STYLES",
    typography: "Typography",
    color: "Color",
    background: "Background",
    size: "Size",
    mainTitle: "Main Title",
    tableHeaders: "Table Headers",
    cellContent: "Cell Content",
    footer: "Footer",
    footerText: "Footer text",
    previewPlaceholder: "Banner will appear here",
    door: "DOOR",
    auditorium: "AUDITORIUM",
    mic1: "MIC 1",
    mic2: "MIC 2",
    group: "GROUP",
    president: "CHAIRMAN",
    speaker: "SPEAKER",
    wtTheme: "WATCHTOWER THEME",
    reader: "READER",
    week: "Week",
    month: "Month",
    year: "Year",
    meetingDay: "Meeting Day(s)",
    createNewMonth: "Create New Month",
    remove: "Remove",
    addWeek: "Add Week",
    previewTitleUshers: "Ushers Program",
    previewTitleCleaning: "Cleaning Program",
    previewTitleWeekend: "Weekend Meeting Schedule",
    previewTitleAudioVideo: "Audio & Video Program",
    responsible: "RESPONSIBLE",
    importExcel: "Import Excel",
    assignedGroup: "ASSIGNED GROUP",
    groupName: "Group Name",
    newMonth: "New Month",
    noDatesTitle: "No dates generated",
    noDatesDesc: "Select days of the week in the month settings (⚙️) to automatically generate the schedule rows.",
    assembly: "ASSEMBLY",
    loadWatchtowerThemes: "Load Watchtower Themes",
    loadingThemes: "Loading themes...",
    themesLoaded: "Watchtower themes loaded successfully",
  },
  pt: {
    appTitle: "Hub Teocrático JW",
    selectTemplate: "Selecionar Modelo",
    templateUshers: "Indicadores",
    templateCleaning: "Limpeza",
    templateWeekend: "Reunião de Fim de Semana",
    templateAudioVideo: "Áudio e Vídeo",
    banner: "Banner",
    uploadBanner: "Carregar Banner",
    content: "CONTEÚDO",
    styles: "ESTILOS",
    typography: "Tipografia",
    color: "Cor",
    background: "Fundo",
    size: "Tamanho",
    mainTitle: "Título Principal",
    tableHeaders: "Cabeçalhos da Tabela",
    cellContent: "Conteúdo da Célula",
    footer: "Rodapé",
    footerText: "Texto do rodapé",
    previewPlaceholder: "O banner aparecerá aqui",
    door: "PORTA",
    auditorium: "AUDITÓRIO",
    mic1: "MICRO 1",
    mic2: "MICRO 2",
    group: "GRUPO",
    president: "PRESIDENTE",
    speaker: "ORADOR",
    wtTheme: "TEMA DE A SENTINELA",
    reader: "LEITOR",
    week: "Semana",
    month: "Mês",
    year: "Ano",
    meetingDay: "Dia(s) da reunião",
    createNewMonth: "Criar Novo Mês",
    remove: "Remover",
    addWeek: "Adicionar Semana",
    previewTitleUshers: "Programa de Indicadores",
    previewTitleCleaning: "Programa de Limpeza",
    previewTitleWeekend: "Programa da Reunião de Fim de Semana",
    previewTitleAudioVideo: "Programa de Áudio e Vídeo",
    responsible: "RESPONSÁVEL",
    importExcel: "Importar Excel",
    assignedGroup: "GRUPO DESIGNADO",
    groupName: "Nome do Grupo",
    newMonth: "Novo Mês",
    noDatesTitle: "Nenhuma data gerada",
    noDatesDesc: "Selecione os dias da semana nas configurações do mês (⚙️) para gerar automaticamente as linhas da programação.",
    assembly: "ASSEMBLEIA",
    loadWatchtowerThemes: "Carregar Temas de A Sentinela",
    loadingThemes: "Carregando temas...",
    themesLoaded: "Temas de A Sentinela carregados com sucesso",
  },
  fr: {
    appTitle: "Hub Teocrático JW",
    selectTemplate: "Sélectionner un Modèle",
    templateUshers: "Accueil",
    templateCleaning: "Nettoyage",
    templateWeekend: "Réunion du week-end",
    templateAudioVideo: "Audio et Vidéo",
    banner: "Bannière",
    uploadBanner: "Télécharger Bannière",
    content: "CONTENU",
    styles: "STYLES",
    typography: "Typographie",
    color: "Couleur",
    background: "Arrière-plan",
    size: "Taille",
    mainTitle: "Titre Principal",
    tableHeaders: "En-têtes de Tableau",
    cellContent: "Contenu des Cellules",
    footer: "Pied de page",
    footerText: "Texte du pied de page",
    previewPlaceholder: "La bannière apparaîtra ici",
    door: "PORTE",
    auditorium: "AUDITORIUM",
    mic1: "MICRO 1",
    mic2: "MICRO 2",
    group: "GROUPE",
    president: "PRÉSIDENT",
    speaker: "ORATEUR",
    wtTheme: "THÈME DE LA TOUR DE GARDE",
    reader: "LECTEUR",
    week: "Semaine",
    month: "Mois",
    year: "Année",
    meetingDay: "Jour(s) de réunion",
    createNewMonth: "Créer un Nouveau Mois",
    remove: "Supprimer",
    addWeek: "Ajouter Semaine",
    previewTitleUshers: "Programme d'Accueil",
    previewTitleCleaning: "Programme de Nettoyage",
    previewTitleWeekend: "Programme de la réunion du week-end",
    previewTitleAudioVideo: "Programme Audio et Vidéo",
    responsible: "RESPONSABLE",
    importExcel: "Importer Excel",
    assignedGroup: "GROUPE ASSIGNÉ",
    groupName: "Nom du Groupe",
    newMonth: "Nouveau Mois",
    noDatesTitle: "Aucune date générée",
    noDatesDesc: "Sélectionnez les jours de la semana dans les paramètres du mois (⚙️) pour générer automatiquement les lignes du programme.",
    assembly: "ASSEMBLÉE",
    loadWatchtowerThemes: "Charger les thèmes de La Tour de Garde",
    loadingThemes: "Chargement des thèmes...",
    themesLoaded: "Thèmes de La Tour de Garde chargés avec succès",
  },
  it: {
    appTitle: "Hub Teocrático JW",
    selectTemplate: "Seleziona Modello",
    templateUshers: "Uscieri",
    templateCleaning: "Pulizie",
    templateWeekend: "Adunanza fine settimana",
    templateAudioVideo: "Audio e Video",
    banner: "Banner",
    uploadBanner: "Carica Banner",
    content: "CONTENUTO",
    styles: "STILI",
    typography: "Tipografia",
    color: "Colore",
    background: "Sfondo",
    size: "Dimensione",
    mainTitle: "Titolo Principale",
    tableHeaders: "Intestazioni Tabella",
    cellContent: "Contenuto Celle",
    footer: "Piè di pagina",
    footerText: "Testo piè di pagina",
    previewPlaceholder: "Il banner apparirà qui",
    door: "PORTA",
    auditorium: "AUDITORIUM",
    mic1: "MICRO 1",
    mic2: "MICRO 2",
    group: "GRUPPO",
    president: "PRESIDENTE",
    speaker: "ORATORE",
    wtTheme: "TEMA DELLA TORRE DI GUARDIA",
    reader: "LETTORE",
    week: "Settimana",
    month: "Mese",
    year: "Anno",
    meetingDay: "Giorno dell'adunanza",
    createNewMonth: "Crea Nuovo Mese",
    remove: "Rimuovi",
    addWeek: "Aggiungi Settimana",
    previewTitleUshers: "Programma Uscieri",
    previewTitleCleaning: "Programma Pulizie",
    previewTitleWeekend: "Programma dell'adunanza del fine settimana",
    previewTitleAudioVideo: "Programma Audio e Video",
    responsible: "RESPONSABILE",
    importExcel: "Importa Excel",
    assignedGroup: "GRUPPO ASSEGNATO",
    groupName: "Nome del Gruppo",
    newMonth: "Nuovo Mese",
    noDatesTitle: "Nessuna data generata",
    noDatesDesc: "Seleziona i giorni della settimana nelle impostazioni del mese (⚙️) per generare automaticamente le righe del programma.",
    assembly: "ASSEMBLEA",
    loadWatchtowerThemes: "Carica temi della Torre di Guardia",
    loadingThemes: "Caricamento temi...",
    themesLoaded: "Temi della Torre di Guardia caricati con successo",
  },
  ru: {
    appTitle: "Hub Teocrático JW",
    selectTemplate: "Выберите шаблон",
    templateUshers: "Распорядители",
    templateCleaning: "Уборка",
    templateWeekend: "Встреча выходного дня",
    templateAudioVideo: "Аудио и видео",
    banner: "Баннер",
    uploadBanner: "Загрузить баннер",
    content: "КОНТЕНТ",
    styles: "СТИЛИ",
    typography: "Типографика",
    color: "Цвет",
    background: "Фон",
    size: "Размер",
    mainTitle: "Главный заголовок",
    tableHeaders: "Заголовки таблицы",
    cellContent: "Содержимое ячеек",
    footer: "Подвал",
    footerText: "Текст подвала",
    previewPlaceholder: "Здесь появится баннер",
    door: "ВХОД",
    auditorium: "ЗАЛ",
    mic1: "МИКР 1",
    mic2: "МИКР 2",
    group: "ГРУППА",
    president: "ПРЕДСЕДАТЕЛЬ",
    speaker: "ДОКЛАДЧИК",
    wtTheme: "ТЕМА СТОРОЖЕВОЙ БАШНИ",
    reader: "ЧТЕЦ",
    week: "Неделя",
    month: "Месяц",
    year: "Год",
    meetingDay: "День встречи",
    createNewMonth: "Создать новый месяц",
    remove: "Удалить",
    addWeek: "Добавить неделю",
    previewTitleUshers: "График распорядителей",
    previewTitleCleaning: "График уборки",
    previewTitleWeekend: "График встречи выходного дня",
    previewTitleAudioVideo: "График аудио и видео",
    responsible: "ОТВЕТСТВЕННЫЙ",
    importExcel: "Импорт из Excel",
    assignedGroup: "НАЗНАЧЕННАЯ ГРУППА",
    groupName: "Название группы",
    newMonth: "Новый месяц",
    noDatesTitle: "Даты не созданы",
    noDatesDesc: "Выберите дни недели в настройках месяца (⚙️), чтобы автоматически создать строки расписания.",
    assembly: "КОНГРЕСС",
    loadWatchtowerThemes: "Загрузить темы Сторожевой Башни",
    loadingThemes: "Загрузка тем...",
    themesLoaded: "Темы Сторожевой Башни успешно загружены",
  },
  pl: {
    appTitle: "Hub Teocrático JW",
    selectTemplate: "Wybierz szablon",
    templateUshers: "Porządkowi",
    templateCleaning: "Sprzątanie",
    templateWeekend: "Zebranie w weekend",
    templateAudioVideo: "Audio i wideo",
    banner: "Baner",
    uploadBanner: "Prześlij baner",
    content: "TREŚĆ",
    styles: "STYLE",
    typography: "Typografia",
    color: "Kolor",
    background: "Tło",
    size: "Rozmiar",
    mainTitle: "Tytuł główny",
    tableHeaders: "Nagłówki tabeli",
    cellContent: "Treść komórek",
    footer: "Stopka",
    footerText: "Tekst stopki",
    previewPlaceholder: "Tutaj pojawi się baner",
    door: "DRZWI",
    auditorium: "AUDYTORIUM",
    mic1: "MIKR 1",
    mic2: "MIKR 2",
    group: "GRUPA",
    president: "PRZEWODNICZĄCY",
    speaker: "MÓWCA",
    wtTheme: "TEMAT STRAŻNICY",
    reader: "LEKTOR",
    week: "Tydzień",
    month: "Miesiąc",
    year: "Rok",
    meetingDay: "Dzień zebrania",
    createNewMonth: "Utwórz nowy miesiąc",
    remove: "Usuń",
    addWeek: "Dodaj tydzień",
    previewTitleUshers: "Program porządkowych",
    previewTitleCleaning: "Program sprzątania",
    previewTitleWeekend: "Program zebrania w weekend",
    previewTitleAudioVideo: "Program audio i wideo",
    responsible: "ODPOWIEDZIALNY",
    importExcel: "Importuj z Excela",
    assignedGroup: "PRZYPISANA GRUPA",
    groupName: "Nazwa grupy",
    newMonth: "Nowy miesiąc",
    noDatesTitle: "Nie wygenerowano dat",
    noDatesDesc: "Wybierz dni tygodnia w ustawieniach miesiąca (⚙️), aby automatycznie wygenerować wiersze harmonogramu.",
    assembly: "ZGROMADZENIE",
    loadWatchtowerThemes: "Wczytaj tematy Strażnicy",
    loadingThemes: "Wczytywanie tematów...",
    themesLoaded: "Pomyślnie załadowano tematy Strażnicy",
  }
};

export const FONTS = [
  "'Poppins', sans-serif",
  'Sora, sans-serif',
  'Arial, sans-serif',
  'Verdana, sans-serif',
  'Georgia, serif',
  "'Times New Roman', serif",
  "'Roboto', sans-serif",
  "'Lato', sans-serif",
  "'Montserrat', sans-serif",
  "'Open Sans', sans-serif",
  "'Merriweather', serif",
  "'Playfair Display', serif"
];

// Helper to get localized month name
export const getMonthName = (monthIndex: number, locale: string = 'es') => {
  const date = new Date(2024, monthIndex, 1);
  const name = new Intl.DateTimeFormat(locale, { month: 'long' }).format(date);
  return name.charAt(0).toUpperCase() + name.slice(1);
};

export const MONTH_NAMES = [
  "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio",
  "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"
];
